name: hrms_frontend
description: HRMS cross-platform client (Flutter + PWA)
publish_to: "none"            # this is a private app

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ─── App packages ─────────────────
  provider: ^6.1.2           # keep the newer provider version
  http: ^1.2.1
  flutter_spinkit: ^5.2.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3   # web + mobile compatible  ✅

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
